# ============================================================================
#  make_ars_examples.R -- regenerate the shipped end-to-end ARS example set
# ============================================================================
#
#  Run FROM THIS FOLDER (inst/ars-examples of the source tree):
#
#      Rscript make_ars_examples.R
#
#  It rebuilds, in place:
#    params_dm_ae.xlsx   compact parameter workbook (the only hand-authored
#                        input of the whole chain)
#    ARS_dm_ae.xlsx      build_ars() + write_ars_xlsx() output
#    adam/ADSL.csv,
#    adam/ADAE.csv       small deterministic CDISC-pilot-flavoured dummy data
#    ARD_Out_dm.R,
#    ARD_Out_ae.R        ARD programmes generated by siera::readARS()
#
#  The displays mirror the rtfreporter showcase articles: a Demographics
#  summary (DM) and Treatment-Emergent Adverse Event summaries (AE) for the
#  three CDISC-pilot arms.  The nested arm x SOC x PT display needs three
#  simultaneous groupings, which the compact format does not support yet
#  (ydisctools issue #6), so the AE output ships flat by-SOC / by-PT /
#  by-severity analyses instead.
# ============================================================================

if (basename(getwd()) != "ars-examples") {
  stop("Run this script from inst/ars-examples (its own folder).")
}
if (!requireNamespace("siera", quietly = TRUE)) {
  stop("The siera package is required to regenerate the ARD programmes.")
}

arms <- c("Placebo", "Xanomeline Low Dose", "Xanomeline High Dose")

# -- 1. Compact parameters ----------------------------------------------------

study <- data.frame(
  key   = c("study_id", "study_title"),
  value = c("CDISCPILOT01", "Example CDISC Pilot Study"),
  stringsAsFactors = FALSE
)

outputs <- data.frame(
  output_id  = c("Out_dm", "Out_ae"),
  name       = c("Summary of Demographic Data",
                 "Summary of Treatment-Emergent Adverse Events"),
  population = c("SAFFL", "SAFFL"),
  group_by   = c("TRT01A", "TRT01A"),
  groups     = rep(paste(arms, collapse = " | "), 2),
  stringsAsFactors = FALSE
)

analyses <- data.frame(
  output_id   = c(rep("Out_dm", 5), rep("Out_ae", 5)),
  analysis_id = sprintf("An_%02d", 1:10),
  name        = c("Number of subjects",
                  "Age (years)",
                  "Age group, n (%)",
                  "Sex, n (%)",
                  "Race, n (%)",
                  "Number of subjects",
                  "Subjects with at least one TEAE, n (%)",
                  "TEAE by System Organ Class, n (%)",
                  "TEAE by Preferred Term, n (%)",
                  "TEAE by severity, n (%)"),
  method      = c("total_n", "continuous_summary", "categorical_summary",
                  "categorical_summary", "categorical_summary",
                  "total_n", "categorical_summary", "categorical_summary",
                  "categorical_summary", "categorical_summary"),
  dataset     = c(rep("ADSL", 5), "ADSL", rep("ADAE", 4)),
  variable    = c("USUBJID", "AGE", rep("USUBJID", 8)),
  population  = "",
  group_by    = c("", "", "TRT01A, AGEGR1", "TRT01A, SEX", "TRT01A, RACE",
                  "", "TRT01A", "TRT01A, ADAE.AEBODSYS",
                  "TRT01A, ADAE.AEDECOD", "TRT01A, ADAE.AESEV"),
  groups      = "",
  groups2     = "",
  where       = c(rep("", 6), rep("TRTEMFL EQ Y", 4)),
  denominator = c("", "", "auto", "auto", "auto",
                  "", "auto", "auto", "auto", "auto"),
  stringsAsFactors = FALSE
)

writexl::write_xlsx(list(Study = study, Outputs = outputs,
                         Analyses = analyses),
                    "params_dm_ae.xlsx")

# -- 2. Expand to the full ARS workbook ---------------------------------------

ars <- ydisctools::build_ars("params_dm_ae.xlsx")
ydisctools::write_ars_xlsx(ars, "ARS_dm_ae.xlsx", overwrite = TRUE)

# -- 3. Deterministic dummy ADaM data -----------------------------------------

set.seed(20260704)
n <- 30
adsl <- data.frame(
  STUDYID = "CDISCPILOT01",
  USUBJID = sprintf("01-701-1%03d", seq_len(n)),
  SAFFL   = c(rep("Y", 28), "N", "N"),
  TRT01A  = rep(arms, each = 10),
  AGE     = sample(51:89, n, replace = TRUE),
  AGEGR1  = NA_character_,
  SEX     = sample(c("F", "M"), n, replace = TRUE),
  RACE    = sample(c("WHITE", "BLACK OR AFRICAN AMERICAN", "ASIAN"),
                   n, replace = TRUE, prob = c(.7, .2, .1)),
  stringsAsFactors = FALSE
)
adsl$AGEGR1 <- cut(adsl$AGE, breaks = c(-Inf, 64, 80, Inf),
                   labels = c("<65", "65-80", ">80")) |> as.character()

soc_pt <- data.frame(
  AEBODSYS = c(rep("GASTROINTESTINAL DISORDERS", 3),
               rep("NERVOUS SYSTEM DISORDERS", 2),
               rep("SKIN AND SUBCUTANEOUS TISSUE DISORDERS", 2),
               "CARDIAC DISORDERS"),
  AEDECOD  = c("DIARRHOEA", "NAUSEA", "VOMITING",
               "HEADACHE", "DIZZINESS",
               "PRURITUS", "RASH",
               "ATRIAL FIBRILLATION"),
  stringsAsFactors = FALSE
)
n_ae <- 55
ae_pick <- sample(nrow(soc_pt), n_ae, replace = TRUE)
adae <- data.frame(
  STUDYID  = "CDISCPILOT01",
  USUBJID  = sample(adsl$USUBJID[adsl$SAFFL == "Y"], n_ae, replace = TRUE),
  TRTEMFL  = sample(c("Y", "N"), n_ae, replace = TRUE, prob = c(.85, .15)),
  AEBODSYS = soc_pt$AEBODSYS[ae_pick],
  AEDECOD  = soc_pt$AEDECOD[ae_pick],
  AESEV    = sample(c("MILD", "MODERATE", "SEVERE"), n_ae,
                    replace = TRUE, prob = c(.5, .35, .15)),
  stringsAsFactors = FALSE
)
adae <- adae[order(adae$USUBJID, adae$AEBODSYS, adae$AEDECOD), ]

dir.create("adam", showWarnings = FALSE)
write.csv(adsl, "adam/ADSL.csv", row.names = FALSE)
write.csv(adae, "adam/ADAE.csv", row.names = FALSE)

# -- 4. Generate the ARD programmes with siera --------------------------------

# adam_path is passed RELATIVE so the emitted readr::read_csv() calls stay
# portable ('adam/ADSL.csv'); run the generated scripts from this folder.
siera::readARS("ARS_dm_ae.xlsx", output_path = ".", adam_path = "adam")

cat("Regenerated:", paste(c("params_dm_ae.xlsx", "ARS_dm_ae.xlsx",
                            "adam/ADSL.csv", "adam/ADAE.csv",
                            list.files(".", pattern = "^ARD_.*[.]R$")),
                          collapse = ", "), "\n")
