# Tests for the bundled STUDY01 pipeline artefacts in inst/sap-pipeline/.
#
# The folder ships the OUTPUT of every stage of the SAP -> TOC -> shells ->
# ARS -> ARD programmes -> tables chain (regenerated by
# make_sap_pipeline.R); these tests only verify the shipped artefacts are
# present and mutually consistent -- nothing is re-run here.

.pipeline_dir <- function() {
  d <- system.file("sap-pipeline", package = "ydisctools")
  skip_if(identical(d, ""), "sap-pipeline folder not installed")
  d
}

test_that("every stage's artefact ships with the package", {
  d <- .pipeline_dir()
  expect_true(file.exists(file.path(d, "README.md")))
  expect_true(file.exists(file.path(d, "make_sap_pipeline.R")))
  expect_true(all(file.exists(file.path(
    d, "adam", c("ADSL.csv", "ADAE.csv", "ADEFF.csv")))))
  expect_true(file.exists(file.path(d, "01_toc", "TOC_STUDY01.xlsx")))
  expect_true(all(file.exists(file.path(
    d, "02_shells", c("shells_STUDY01.xlsx", "shells_STUDY01.rtf")))))
  expect_true(file.exists(file.path(d, "03_ars", "ARS_STUDY01.xlsx")))
  expect_length(list.files(file.path(d, "04_programmes"),
                           pattern = "^ARD_Out_.*[.]R$"), 10)
  expect_true(file.exists(file.path(d, "05_ard", "ARD_STUDY01.csv")))
  expect_true(all(file.exists(file.path(
    d, "06_tfl", c("make_tfl.R", "TFL_STUDY01.rtf")))))
})

test_that("the shipped TOC drives 10 displays with the company numbering", {
  d <- .pipeline_dir()
  toc <- readxl::read_excel(file.path(d, "01_toc", "TOC_STUDY01.xlsx"),
                            sheet = "TOC")
  expect_equal(nrow(toc), 10)
  expect_equal(sum(toc$display_type == "custom"), 2)

  p <- ars_from_toc(file.path(d, "01_toc", "TOC_STUDY01.xlsx"),
                    section_map = c(baseline = "15.1", efficacy = "15.2",
                                    safety_ae = "15.3.1",
                                    safety_lab = "15.3.4"))
  expect_equal(p$toc$toc_no,
               c("15.1.1", "15.1.2", "15.1.3",
                 "15.3.1.1", "15.3.1.2", "15.3.1.3", "15.3.1.4", "15.3.1.5",
                 "15.2.1", "15.2.2"))
})

test_that("the shipped ARD covers all 10 outputs and is per-group correct", {
  d <- .pipeline_dir()
  ard <- read.csv(file.path(d, "05_ard", "ARD_STUDY01.csv"),
                  stringsAsFactors = FALSE)
  expect_length(unique(ard$OutputId), 10)

  # flat categorical analyses use per-group percentage denominators: every
  # any-TEAE percentage must equal n / (that arm's big N), not n / total N
  adsl <- read.csv(file.path(d, "adam", "ADSL.csv"), stringsAsFactors = FALSE)
  bign <- vapply(split(adsl[adsl$SAFFL == "Y", "USUBJID"],
                       adsl[adsl$SAFFL == "Y", "TRT01A"]), length, numeric(1))
  flat <- ard[ard$OutputId == "Out_ae_ov" & ard$variable == ".flag_", ]
  expect_gt(nrow(flat), 0)
  n_rows <- flat[flat$stat_name == "n", ]
  p_rows <- flat[flat$stat_name == "p", ]
  key <- paste(n_rows$AnalysisId, n_rows$group1_level)
  expect_equal(
    p_rows$stat[match(key, paste(p_rows$AnalysisId, p_rows$group1_level))],
    n_rows$stat / bign[n_rows$group1_level],
    ignore_attr = TRUE, tolerance = 1e-8
  )
})

test_that("the shipped TFL document renders every display", {
  d <- .pipeline_dir()
  rtf <- readLines(file.path(d, "06_tfl", "TFL_STUDY01.rtf"), warn = FALSE)
  txt <- paste(rtf, collapse = "\n")
  for (no in c("15.1.1", "15.1.2", "15.1.3",
               "15.3.1.1", "15.3.1.2", "15.3.1.3", "15.3.1.4", "15.3.1.5",
               "15.2.1", "15.2.2")) {
    expect_true(grepl(paste0("Table ", no), txt, fixed = TRUE), info = no)
  }
})
