# ============================================================================
#  make_sap_pipeline.R -- regenerate the bundled STUDY01 pipeline artefacts
#  (ydisctools issue #31)
# ============================================================================
#
#  Run FROM THIS FOLDER (inst/sap-pipeline of the source tree):
#
#      Rscript make_sap_pipeline.R
#
#  It rebuilds, in place, one artefact per stage of the
#  SAP -> TOC -> shells -> ARS -> ARD programmes -> tables chain, so the
#  installed package carries the *output* of every stage -- readers of the
#  "From the SAP to the tables" article can inspect each artefact without
#  executing anything:
#
#      adam/                       deterministic STUDY01 dummy ADaM
#                                  (ADSL / ADAE / ADEFF; the input data)
#      01_toc/TOC_STUDY01.xlsx     the reviewed TFL TOC workbook (the hub)
#      02_shells/shells_STUDY01.*  mock shells (xlsx + rtf)
#      03_ars/ARS_STUDY01.xlsx     full ARS metadata workbook
#      04_programmes/ARD_Out_*.R   ARD programmes generated by siera::readARS()
#      05_ard/ARD_STUDY01.csv      the combined study-level ARD
#      06_tfl/TFL_STUDY01.rtf      final tables, rendered by the bundled
#                                  table programme 06_tfl/make_tfl.R
#
#  Stage inputs: the synthetic SAP and company CSR template live in
#  ../ars-doc-samples (regenerate them first with make_doc_samples.R when
#  they change).  The review edits applied to the drafted TOC below are the
#  same ones the article walks through -- they materialise the
#  deliberately-manual review step so the chain stays runnable.
# ============================================================================

if (basename(getwd()) != "sap-pipeline") {
  stop("Run this script from inst/sap-pipeline (its own folder).")
}
for (pkg in c("ydisctools", "officer", "siera", "openxlsx", "rtfreporter")) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Package '", pkg, "' is required to regenerate the artefacts.")
  }
}
library(ydisctools)

docs <- "../ars-doc-samples"
if (!file.exists(file.path(docs, "sample_sap.docx"))) {
  stop("Expected the sample documents in ", docs,
       " (run make_doc_samples.R there first).")
}
for (d in c("adam", "01_toc", "02_shells", "03_ars", "04_programmes",
            "05_ard", "06_tfl")) {
  dir.create(d, showWarnings = FALSE)
}

arms <- c("Placebo", "Xanomeline Low Dose", "Xanomeline High Dose")

# -- Stage 0: deterministic dummy ADaM data (the input of the run) ------------
#
#  60 subjects, 20 per arm.  Every variable a planned display needs is
#  carried: demographics, disposition (EOSSTT / DCSREAS), exposure
#  (TRTDURD / CUMDOSE), adverse events with seriousness (AESER), and the
#  two efficacy parameters (PRIMEP / SECEP with responder flag CRIT1FL).

set.seed(20260705)
n <- 60
adsl <- data.frame(
  STUDYID = "STUDY01",
  USUBJID = sprintf("S01-%03d", seq_len(n)),
  ITTFL   = "Y",                       # all randomised
  SAFFL   = "Y",
  TRT01A  = rep(arms, each = n / 3),
  AGE     = sample(52:88, n, replace = TRUE),
  AGEGR1  = NA_character_,
  SEX     = sample(c("F", "M"), n, replace = TRUE),
  RACE    = sample(c("WHITE", "BLACK OR AFRICAN AMERICAN", "ASIAN"),
                   n, replace = TRUE, prob = c(.7, .2, .1)),
  ETHNIC  = sample(c("HISPANIC OR LATINO", "NOT HISPANIC OR LATINO"),
                   n, replace = TRUE, prob = c(.12, .88)),
  stringsAsFactors = FALSE
)
adsl$AGEGR1 <- as.character(cut(adsl$AGE, breaks = c(-Inf, 64, 80, Inf),
                                labels = c("<65", "65-80", ">80")))
adsl$SAFFL[sample(n, 3)] <- "N"        # randomised but never treated
adsl$EOSSTT <- ifelse(
  adsl$SAFFL == "N", "DISCONTINUED",
  sample(c("COMPLETED", "DISCONTINUED"), n, replace = TRUE, prob = c(.8, .2)))
adsl$DCSREAS <- ifelse(
  adsl$EOSSTT == "COMPLETED", "",
  sample(c("ADVERSE EVENT", "WITHDRAWAL BY SUBJECT", "LOST TO FOLLOW-UP",
           "LACK OF EFFICACY"), n, replace = TRUE))
dur <- ifelse(adsl$EOSSTT == "COMPLETED", 168L,
              sample(14:150, n, replace = TRUE))
adsl$TRTDURD <- ifelse(adsl$SAFFL == "Y", dur, NA_integer_)
dose_per_day <- c(0, 54, 81)[match(adsl$TRT01A, arms)]
adsl$CUMDOSE <- ifelse(adsl$SAFFL == "Y", dose_per_day * adsl$TRTDURD,
                       NA_real_)

soc_pt <- data.frame(
  AEBODSYS = c(rep("GASTROINTESTINAL DISORDERS", 3),
               rep("NERVOUS SYSTEM DISORDERS", 3),
               rep("SKIN AND SUBCUTANEOUS TISSUE DISORDERS", 2),
               "CARDIAC DISORDERS",
               "INFECTIONS AND INFESTATIONS"),
  AEDECOD  = c("DIARRHOEA", "NAUSEA", "VOMITING",
               "HEADACHE", "DIZZINESS", "SOMNOLENCE",
               "PRURITUS", "RASH",
               "ATRIAL FIBRILLATION",
               "NASOPHARYNGITIS"),
  stringsAsFactors = FALSE
)
n_ae <- 140
treated <- adsl[adsl$SAFFL == "Y", c("USUBJID", "TRT01A")]
ae_weight <- c(.8, 1, 1.3)[match(treated$TRT01A, arms)]  # dose-dependent rate
ae_subj <- sample(treated$USUBJID, n_ae, replace = TRUE, prob = ae_weight)
ae_pick <- sample(nrow(soc_pt), n_ae, replace = TRUE)
adae <- data.frame(
  STUDYID  = "STUDY01",
  USUBJID  = ae_subj,
  TRTEMFL  = sample(c("Y", "N"), n_ae, replace = TRUE, prob = c(.9, .1)),
  AEBODSYS = soc_pt$AEBODSYS[ae_pick],
  AEDECOD  = soc_pt$AEDECOD[ae_pick],
  AESEV    = sample(c("MILD", "MODERATE", "SEVERE"), n_ae,
                    replace = TRUE, prob = c(.5, .35, .15)),
  AESER    = sample(c("Y", "N"), n_ae, replace = TRUE, prob = c(.12, .88)),
  stringsAsFactors = FALSE
)
adae <- adae[order(adae$USUBJID, adae$AEBODSYS, adae$AEDECOD), ]

# efficacy: change from baseline at Week 24, dose-dependent improvement
eff_mean <- function(means) means[match(adsl$TRT01A, arms)]
prim <- round(rnorm(n, mean = eff_mean(c(0.7, 2.6, 4.2)), sd = 2.8), 1)
secv <- round(rnorm(n, mean = eff_mean(c(0.3, 1.1, 1.8)), sd = 1.4), 1)
adeff <- rbind(
  data.frame(
    STUDYID = "STUDY01", USUBJID = adsl$USUBJID, PARAMCD = "PRIMEP",
    PARAM   = "Cognition Total Score Change from Baseline at Week 24",
    AVAL    = prim,
    CRIT1FL = ifelse(prim >= 4, "Y", "N"),   # responder: >= 4-point gain
    stringsAsFactors = FALSE),
  data.frame(
    STUDYID = "STUDY01", USUBJID = adsl$USUBJID, PARAMCD = "SECEP",
    PARAM   = "Clinician Global Impression Change from Baseline at Week 24",
    AVAL    = secv,
    CRIT1FL = ifelse(secv > 0, "Y", "N"),    # responder: any improvement
    stringsAsFactors = FALSE)
)
adeff <- adeff[order(adeff$USUBJID, adeff$PARAMCD), ]

write.csv(adsl,  "adam/ADSL.csv",  row.names = FALSE)
write.csv(adae,  "adam/ADAE.csv",  row.names = FALSE)
write.csv(adeff, "adam/ADEFF.csv", row.names = FALSE)

# -- Stage 1: numbering map + draft TOC from the Word documents ---------------

csr   <- read_csr_map(file.path(docs, "sample_csr_template.docx"))
draft <- read_sap_toc(file.path(docs, "sample_sap.docx"))
stopifnot(nrow(draft$toc) == 10)

# -- the review step (the same edits the article walks through) ---------------

toc <- draft$toc
toc$output_id <- c("Out_dm", "Out_ds", "Out_ex",
                   "Out_ae_ov", "Out_ae_soc", "Out_ae_pt", "Out_ae_sev",
                   "Out_ae_ser", "Out_eff_pri", "Out_eff_sec")
toc$population <- ifelse(toc$population == "ITT", "ITTFL", "SAFFL")
toc$group_by <- "TRT01A"
toc$groups   <- paste(arms, collapse = " | ")
# the serious-AE display reuses the ae_soc recipe narrowed to serious events
toc$where[toc$output_id == "Out_ae_ser"] <- "AESER EQ Y"

# hand-authored analyses for the two custom efficacy displays
eff_analyses <- function(output_id, paramcd) {
  data.frame(
    output_id   = output_id,
    analysis_id = "",
    name        = c("Number of subjects",
                    "Change from baseline at Week 24",
                    "Responders, n (%)"),
    method      = c("total_n", "continuous_summary", "categorical_summary"),
    dataset     = c("ADSL", "ADEFF", "ADEFF"),
    variable    = c("USUBJID", "AVAL", "USUBJID"),
    population  = "",
    group_by    = c("", "", "TRT01A, CRIT1FL"),
    groups      = "",
    groups2     = "",
    where       = c("", paste("PARAMCD EQ", paramcd),
                    paste("PARAMCD EQ", paramcd)),
    denominator = c("", "", "auto"),
    stringsAsFactors = FALSE
  )
}
analyses <- rbind(eff_analyses("Out_eff_pri", "PRIMEP"),
                  eff_analyses("Out_eff_sec", "SECEP"))

study <- data.frame(
  key   = c("study_id", "study_title"),
  value = c("STUDY01", "A Randomised Study of Xanomeline in Dementia"),
  stringsAsFactors = FALSE
)
toc_file <- "01_toc/TOC_STUDY01.xlsx"
writexl::write_xlsx(list(Study = study, TOC = toc, Analyses = analyses),
                    toc_file)

# -- Stage 2: mock shells (xlsx + rtf) -----------------------------------------

ars_mock(toc_file, "02_shells/shells_STUDY01.xlsx",
         section_map = csr$section_map, overwrite = TRUE)
ars_mock(toc_file, "02_shells/shells_STUDY01.rtf", format = "rtf",
         section_map = csr$section_map, overwrite = TRUE)

# -- Stage 3: full ARS metadata workbook ---------------------------------------

params <- ars_from_toc(toc_file, section_map = csr$section_map)
ars <- build_ars(params)
write_ars_xlsx(ars, "03_ars/ARS_STUDY01.xlsx", overwrite = TRUE)

# -- Stages 4 + 5: ARD programmes (siera) and the combined study ARD -----------

unlink(list.files("04_programmes", pattern = "^ARD_.*[.]R$",
                  full.names = TRUE))
ard <- ars_generate_ard("03_ars/ARS_STUDY01.xlsx", adam_path = "adam",
                        output_path = "04_programmes")
stopifnot(length(unique(ard$OutputId)) == 10)

keep <- intersect(c("OutputId", "AnalysisId", "MethodId",
                    "group1", "group1_level", "group2", "group2_level",
                    "variable", "variable_level", "stat_name", "stat_label",
                    "stat"), names(ard))
ard_flat <- as.data.frame(ard)[, keep]
ard_flat$stat <- vapply(ard_flat$stat, function(v) {
  if (is.null(v) || length(v) == 0) NA_real_ else
    suppressWarnings(as.numeric(v[[1]]))
}, numeric(1))
write.csv(ard_flat, "05_ard/ARD_STUDY01.csv", row.names = FALSE, na = "")

# -- Stage 6: the table programme ----------------------------------------------

source("06_tfl/make_tfl.R")

cat("Regenerated the STUDY01 pipeline artefacts:\n",
    paste0("  ", c("adam/ADSL.csv, adam/ADAE.csv, adam/ADEFF.csv",
                   "01_toc/TOC_STUDY01.xlsx",
                   "02_shells/shells_STUDY01.xlsx, 02_shells/shells_STUDY01.rtf",
                   "03_ars/ARS_STUDY01.xlsx",
                   paste0("04_programmes/ (",
                          length(list.files("04_programmes")), " programmes)"),
                   "05_ard/ARD_STUDY01.csv",
                   "06_tfl/TFL_STUDY01.rtf"),
           collapse = "\n"), "\n", sep = "")
