# ============================================================================
#  ars_from_code.R -- recover compact ARS parameters from existing R
#  table / ARD programmes (static AST analysis; no code is executed)
# ============================================================================
#
#  ars_params_from_code() reads one or more R programmes that build clinical
#  summaries with {cards} / {cardx} (hand-written table programmes, or ARD
#  programmes generated by siera::readARS()) and drafts the compact parameter
#  set consumed by build_ars().  The draft is meant to be REVIEWED and
#  modified -- everything the static analysis cannot decide is surfaced as an
#  explicit note (REVIEW / ASSUMED / LIMITATION / MAPPED) instead of being
#  guessed silently.
#
#  Method mapping targets cards / cardx calls only (maintainer decision,
#  issue #10); display furniture (page headers / footers, titles, footnotes,
#  the row-label column header) is additionally captured from rtfreporter
#  idioms where statically possible and lands on the params `displays`
#  element, which build_ars() turns into the ARS Outputs / Displays /
#  GlobalDisplaySections sheets.
# ============================================================================

#' Recover compact ARS parameters from R programmes
#'
#' Statically analyses one or more R programmes (no code is executed) and
#' drafts the compact parameter set for [build_ars()]: analyses are recovered
#' from \pkg{cards} / \pkg{cardx} calls, populations / subsets / group levels
#' from the \code{dplyr::filter()} pipeline feeding them, and display
#' furniture (titles, footnotes, page headers / footers, the row-label column
#' header) from \pkg{rtfreporter} idioms where present.  Each input file
#' becomes one output (display).
#'
#' Supported analysis calls: \code{ard_summary()} / \code{ard_continuous()},
#' \code{ard_tabulate()} / \code{ard_categorical()} (including the
#' siera-generated subject-count and big-N idioms), \code{ard_stack()}
#' (\code{.by}, \code{.total_n}), \code{ard_stack_hierarchical()} (including
#' \code{over_variables = TRUE}; a nested hierarchy is flattened with a
#' LIMITATION note), and the cardx tests
#' \code{ard_stats_fisher_test/chisq_test/aov/anova/oneway_test/prop_test()}
#' (mapped onto the bundled method catalog).  Anything else is skipped with a
#' note.
#'
#' The result is a DRAFT: review the \code{notes} element (and the
#' \code{Notes} sheet written by [write_ars_params()]) before building an ARS
#' from it.
#'
#' @param paths Character vector of R source files (one output per file).
#' @param output_id Optional character vector (same length as \code{paths})
#'   of output IDs; default derives them from the file names.
#' @param output_name Optional character vector of output display names;
#'   default uses the file names.
#'
#' @return A named list with elements \code{outputs}, \code{analyses},
#'   \code{displays} (may have zero rows) and \code{notes} (character) --
#'   the first three in the compact parameter layout of
#'   [ars_param_template()].
#'
#' @seealso [write_ars_params()] to save the draft as a parameter workbook,
#'   [build_ars()] to expand it into ARS metadata.
#'
#' @examples
#' # Recover parameters from a shipped siera-generated ARD programme:
#' src <- file.path(system.file("ars-examples", package = "ydisctools"),
#'                  "ARD_Out_dm.R")
#' params <- ars_params_from_code(src, output_id = "Out_dm",
#'                                output_name = "Summary of Demographic Data")
#' params$analyses
#' params$notes
#'
#' @export
ars_params_from_code <- function(paths, output_id = NULL, output_name = NULL) {
  if (!is.character(paths) || length(paths) == 0) {
    stop("`paths` must be one or more R source file paths.", call. = FALSE)
  }
  missing_files <- paths[!file.exists(paths)]
  if (length(missing_files) > 0) {
    stop("Source file(s) not found: ",
         paste(missing_files, collapse = ", "), ".", call. = FALSE)
  }
  if (is.null(output_id)) {
    output_id <- paste0("Out_", gsub("[^A-Za-z0-9_]", "_",
                                     sub("[.][^.]*$", "", basename(paths))))
  }
  if (is.null(output_name)) output_name <- basename(paths)
  if (length(output_id) != length(paths) ||
      length(output_name) != length(paths)) {
    stop("`output_id` / `output_name` must match `paths` in length.",
         call. = FALSE)
  }

  parts <- lapply(seq_along(paths), function(i) {
    .apc_extract_file(paths[i], output_id[i], output_name[i])
  })

  outputs <- do.call(rbind, lapply(parts, `[[`, "outputs"))
  analyses <- do.call(rbind, lapply(parts, `[[`, "analyses"))
  displays <- do.call(rbind, lapply(parts, `[[`, "displays"))
  notes <- unique(unlist(lapply(parts, `[[`, "notes")))

  if (!is.null(analyses) && nrow(analyses) > 0) {
    analyses$analysis_id <- sprintf("An_%02d", seq_len(nrow(analyses)))
  }
  list(outputs = outputs, analyses = analyses, displays = displays,
       notes = notes)
}

#' Write a recovered parameter set to a compact parameter workbook
#'
#' Saves the result of [ars_params_from_code()] (or any compatible list with
#' \code{outputs} / \code{analyses}, optionally \code{displays} and
#' \code{notes}) as a workbook in the [ars_param_template()] layout, with the
#' review notes on an extra \code{Notes} sheet.  The file can be edited and
#' read back with [read_ars_params()], then expanded with [build_ars()].
#'
#' @param params Named list with \code{outputs} and \code{analyses} data
#'   frames; optional \code{study}, \code{displays} and \code{notes}.
#' @param path File path of the workbook to write (\code{.xlsx}).
#' @param overwrite Logical; overwrite an existing file? Default \code{FALSE}.
#'
#' @return The path, invisibly.
#'
#' @seealso [ars_params_from_code()], [read_ars_params()], [build_ars()]
#'
#' @examples
#' src <- file.path(system.file("ars-examples", package = "ydisctools"),
#'                  "ARD_Out_dm.R")
#' params <- ars_params_from_code(src, output_id = "Out_dm",
#'                                output_name = "Summary of Demographic Data")
#' tmp <- file.path(tempdir(), "recovered_params.xlsx")
#' write_ars_params(params, tmp, overwrite = TRUE)
#'
#' @export
write_ars_params <- function(params, path, overwrite = FALSE) {
  if (!is.list(params) ||
      !all(c("outputs", "analyses") %in% names(params)) ||
      is.null(params$outputs) || is.null(params$analyses)) {
    stop("`params` must be a list with `outputs` and `analyses` data frames.",
         call. = FALSE)
  }
  if (file.exists(path) && !overwrite) {
    stop("File already exists: '", path, "'. Set overwrite = TRUE to replace.",
         call. = FALSE)
  }
  sheets <- list()
  if (!is.null(params$study)) sheets$Study <- as.data.frame(params$study)
  sheets$Outputs <- as.data.frame(params$outputs)
  sheets$Analyses <- as.data.frame(params$analyses)
  if (!is.null(params$displays) && nrow(params$displays) > 0) {
    sheets$Displays <- as.data.frame(params$displays)
  }
  if (!is.null(params$notes) && length(params$notes) > 0) {
    sheets$Notes <- data.frame(note = params$notes, stringsAsFactors = FALSE)
  }
  writexl::write_xlsx(sheets, path)
  invisible(path)
}

# ============================================================================
#  Internal machinery (prefix .apc_ = "ARS params from code")
# ============================================================================

.apc_null_default <- function(a, b) if (is.null(a)) b else a

# per-file extraction
.apc_extract_file <- function(path, output_id, output_name) {
  exprs <- parse(file = path, keep.source = FALSE)

  st <- new.env(parent = emptyenv())
  st$notes <- character(0)
  st$rows <- list()                     # analysis rows
  st$disp <- list()                     # display subsection rows
  st$ds <- list()                       # symbol -> list(dataset, conds, sym)
  st$values <- list()                   # symbol -> character vector constants
  st$note <- function(msg) st$notes <- c(st$notes, msg)

  for (e in exprs) .apc_scan(e, st)

  # de-duplicate analyses extracted more than once (e.g. the two dataDriven
  # branches of a siera method template both call ard_tabulate())
  rows <- st$rows
  if (length(rows) > 0) {
    sig <- vapply(rows, function(r) {
      paste(r$method, r$dataset, r$variable, r$group_by, r$where,
            r$denominator, r$population, sep = "\r")
    }, character(1))
    rows <- rows[!duplicated(sig)]
  }

  analyses <- NULL
  if (length(rows) > 0) {
    analyses <- do.call(rbind, lapply(seq_along(rows), function(i) {
      r <- rows[[i]]
      data.frame(
        output_id = output_id,
        analysis_id = sprintf("An_%02d", i),
        name = r$name, method = r$method, dataset = r$dataset,
        variable = r$variable, population = r$population,
        group_by = r$group_by, groups = r$groups, groups2 = "",
        where = r$where, denominator = r$denominator,
        stringsAsFactors = FALSE
      )
    }))
  } else {
    st$note(paste0("No convertible cards/cardx calls found in ",
                   basename(path), "."))
  }

  displays <- NULL
  if (length(st$disp) > 0) {
    displays <- do.call(rbind, lapply(st$disp, as.data.frame,
                                      stringsAsFactors = FALSE))
    displays$output_id <- output_id
    displays <- displays[, c("output_id", "section_type", "order", "text")]
    # order within each section type, in extraction order
    ord <- integer(nrow(displays))
    for (tp in unique(displays$section_type)) {
      idx <- which(displays$section_type == tp)
      ord[idx] <- seq_along(idx)
    }
    displays$order <- ord
  }

  outputs <- data.frame(output_id = output_id, name = output_name,
                        population = "", group_by = "", groups = "",
                        stringsAsFactors = FALSE)
  list(outputs = outputs, analyses = analyses, displays = displays,
       notes = unique(st$notes))
}

# -- expression scanning ------------------------------------------------------

# depth-first scan: records assignments (dataset pipelines / constants) at ANY
# nesting depth (siera wraps its statements in if-blocks) and dispatches
# handled calls.
.apc_scan <- function(e, st) {
  if (!is.call(e)) return(invisible())
  f <- .apc_fname(e)
  if (f %in% c("<-", "=", "<<-") && length(e) == 3) {
    lhs <- e[[2]]; rhs <- e[[3]]
    if (is.name(lhs)) {
      v <- .apc_literal_chr(rhs)
      if (!is.null(v)) st$values[[as.character(lhs)]] <- v
      info <- .apc_pipeline_info(rhs, st)
      if (!is.null(info)) st$ds[[as.character(lhs)]] <- info
      # a column-header assignment carries the row-label header text
      if (grepl("col_header", as.character(lhs), fixed = TRUE)) {
        .apc_capture_col_header(rhs, st)
        return(invisible())
      }
    }
    .apc_scan(rhs, st)
    return(invisible())
  }
  if (f == "ard_stack") { .apc_h_stack(e, st); return(invisible()) }
  if (f == "ard_stack_hierarchical") { .apc_h_stack_hier(e, st); return(invisible()) }
  if (f %in% c("ard_summary", "ard_continuous")) {
    .apc_h_continuous(e, st, ctx = NULL); return(invisible())
  }
  if (f %in% c("ard_tabulate", "ard_categorical")) {
    .apc_h_tabulate(e, st, ctx = NULL); return(invisible())
  }
  if (f %in% names(.apc_cardx_map)) { .apc_h_cardx(e, st); return(invisible()) }
  if (f %in% c("rtf_header", "rtf_footer")) {
    .apc_h_furniture(e, st, kind = f)
    return(invisible())
  }
  if (f %in% c("rtf_titles", "rtf_footnotes", "rtf_tables")) {
    .apc_h_text_args(e, st)
    # fall through: rtf_tables(...) may still hold parseable inner calls
  }
  if (grepl("^ard_", f)) {
    st$note(paste0("Unsupported ARD function skipped: ", f, "()"))
  }
  for (i in seq_along(e)[-1]) {
    # tryCatch guards against empty call arguments (e.g. `x[, 1]`)
    ok <- tryCatch(is.call(e[[i]]), error = function(err) FALSE)
    if (ok) .apc_scan(e[[i]], st)
  }
  invisible()
}

.apc_fname <- function(e) {
  h <- e[[1]]
  if (is.name(h)) return(as.character(h))
  if (is.call(h) && is.name(h[[1]]) &&
      as.character(h[[1]]) %in% c("::", ":::")) {
    return(as.character(h[[3]]))
  }
  ""
}

.apc_arg <- function(e, name) {
  nm <- names(e)
  if (!is.null(nm)) {
    hit <- which(nm == name)
    if (length(hit) == 1) return(e[[hit]])
  }
  NULL
}

# first unnamed argument (conventionally `data`)
.apc_arg_data <- function(e) {
  d <- .apc_arg(e, "data")
  if (!is.null(d)) return(d)
  nm <- names(e); if (is.null(nm)) nm <- rep("", length(e))
  for (i in seq_along(e)[-1]) {
    if (nm[i] == "" && !is.call(e[[i]])) return(e[[i]])
  }
  for (i in seq_along(e)[-1]) if (nm[i] == "") return(e[[i]])
  NULL
}

# character values of an expression: "x", c("a","b"), symbol, c(SYM1, SYM2)
.apc_chr_vec <- function(e, st = NULL) {
  if (is.null(e)) return(character(0))
  if (is.character(e)) return(e)
  if (is.name(e)) {
    v <- as.character(e)
    if (!is.null(st) && !is.null(st$values[[v]])) return(st$values[[v]])
    return(v)
  }
  if (is.call(e) && .apc_fname(e) == "c") {
    return(unlist(lapply(as.list(e)[-1], .apc_chr_vec, st = st)))
  }
  paste(deparse(e), collapse = " ")
}

.apc_literal_chr <- function(e) {
  if (is.character(e)) return(e)
  if (is.call(e) && .apc_fname(e) == "c") {
    parts <- as.list(e)[-1]
    if (all(vapply(parts, is.character, logical(1)))) return(unlist(parts))
  }
  NULL
}

# -- dataset pipeline tracking ------------------------------------------------

# Resolve a pipeline (x |> filter() |> mutate(), possibly pkg::data) to its
# base dataset and the filter conditions applied along the way.  The native
# pipe |> is already collapsed by the parser (a |> f(b) parses as f(a, b)).
.apc_pipeline_info <- function(e, st) {
  conds <- list()
  cur <- e
  repeat {
    if (is.name(cur)) {
      sym <- as.character(cur)
      base <- st$ds[[sym]]
      if (!is.null(base)) {
        return(list(dataset = base$dataset,
                    conds = c(base$conds, rev(conds)), sym = sym))
      }
      return(list(dataset = toupper(sym), conds = rev(conds), sym = sym))
    }
    if (is.call(cur) && is.name(cur[[1]]) &&
        as.character(cur[[1]]) %in% c("::", ":::")) {
      # a bare pkg::dataset reference (NOT a namespaced function call)
      return(list(dataset = toupper(as.character(cur[[3]])),
                  conds = rev(conds), sym = NA_character_))
    }
    if (!is.call(cur)) return(NULL)
    f <- .apc_fname(cur)
    if (f %in% c("%>%")) {
      rhs <- cur[[3]]
      if (is.call(rhs) && .apc_fname(rhs) == "filter") {
        conds <- c(conds, as.list(rhs)[-1])
      }
      cur <- cur[[2]]
      next
    }
    if (f == "filter") {                # filter(data, ...) / piped filter
      conds <- c(conds, as.list(cur)[setdiff(seq_along(cur), c(1, 2))])
      cur <- cur[[2]]
      next
    }
    if (f %in% c("mutate", "arrange", "select", "distinct", "group_by",
                 "unique", "rename", "ungroup", "subset")) {
      cur <- cur[[2]]
      next
    }
    if (f %in% c("merge", "left_join", "inner_join")) {
      st$note(paste0("REVIEW: a dataset is built by ", f, "(); the dataset ",
                     "name was approximated from the join's left side - ",
                     "check the `dataset` column."))
      cur <- cur[[2]]
      next
    }
    return(NULL)
  }
}

.apc_data_info <- function(e, st) {
  if (is.null(e)) return(NULL)
  .apc_pipeline_info(e, st)
}

# -- filter-condition classification ------------------------------------------

.apc_cond_mini <- function(e, st) {
  if (!is.call(e)) return(NA_character_)
  op <- as.character(e[[1]])[1]
  map <- c("==" = "EQ", "!=" = "NE", ">" = "GT", ">=" = "GE",
           "<" = "LT", "<=" = "LE")
  if (op %in% names(map) && is.name(e[[2]])) {
    val <- e[[3]]
    if (is.character(val) || is.numeric(val)) {
      return(paste(as.character(e[[2]]), map[[op]], as.character(val)))
    }
  }
  if (op == "%in%" && is.name(e[[2]])) {
    vals <- .apc_chr_vec(e[[3]], st)
    if (length(vals) > 0) {
      return(paste(as.character(e[[2]]), "IN", paste(vals, collapse = "|")))
    }
  }
  NA_character_
}

.apc_pop_flags <- c("SAFFL", "ITTFL", "FASFL", "PPROTFL", "RANDFL", "ENRLFL",
                    "COMPLFL")

.apc_split_conds <- function(conds, group_vars, st) {
  out <- list(population = character(0), where = character(0), groups = "")
  for (cnd in conds) {
    mini <- .apc_cond_mini(cnd, st)
    if (is.na(mini)) {
      st$note(paste0("REVIEW: condition not convertible: `",
                     paste(deparse(cnd), collapse = " "), "`"))
      next
    }
    var <- strsplit(mini, " ", fixed = TRUE)[[1]][1]
    if (var %in% group_vars && grepl(" IN ", mini, fixed = TRUE)) {
      # a filter on the grouping variable = the pre-defined group levels
      out$groups <- gsub("|", " | ", sub("^.* IN ", "", mini), fixed = TRUE)
    } else if (var %in% .apc_pop_flags) {
      out$population <- c(out$population, var)
    } else {
      out$where <- c(out$where, mini)
    }
  }
  out
}

# -- analysis emission --------------------------------------------------------

.apc_ctx_of <- function(e, st, ctx) {
  data_e <- .apc_arg_data(e)
  info <- if (!is.null(data_e)) .apc_data_info(data_e, st) else ctx$info
  by <- .apc_chr_vec(.apc_null_default(.apc_arg(e, "by"),
                                       .apc_arg(e, "strata")), st)
  if (length(by) == 0 && !is.null(ctx$by)) by <- ctx$by
  list(info = info, by = by)
}

.apc_emit <- function(st, method, variable, group_vars, info, name,
                      denominator = "") {
  info <- .apc_null_default(info, list(dataset = "UNKNOWN", conds = list()))
  sp <- .apc_split_conds(info$conds, group_vars, st)
  if (length(sp$population) == 0) {
    st$note(paste0("REVIEW: no population flag found for '", name,
                   "' - set `population` manually."))
  }
  st$rows[[length(st$rows) + 1L]] <- list(
    name = name, method = method, dataset = info$dataset,
    variable = variable,
    population = if (length(sp$population)) sp$population[1] else "",
    group_by = paste(group_vars, collapse = ", "),
    groups = sp$groups,
    where = paste(unique(sp$where), collapse = "; "),
    denominator = denominator
  )
}

.apc_h_continuous <- function(e, st, ctx = NULL) {
  cx <- .apc_ctx_of(e, st, ctx)
  vars <- .apc_chr_vec(.apc_arg(e, "variables"), st)
  for (v in vars) {
    .apc_emit(st, "continuous_summary", v, cx$by, cx$info,
              name = paste0(v, " (continuous)"))
  }
  if (!is.null(.apc_arg(e, "statistic"))) {
    st$note(paste0("REVIEW: custom `statistic=` on ard_summary(",
                   paste(vars, collapse = ","),
                   ") - the catalog continuous_summary emits its own fixed ",
                   "stat set (N/mean/sd/median/p25/p75/min/max)."))
  }
}

.apc_h_tabulate <- function(e, st, ctx = NULL) {
  cx <- .apc_ctx_of(e, st, ctx)
  vars <- .apc_chr_vec(.apc_arg(e, "variables"), st)
  den <- .apc_arg(e, "denominator")

  # ydisctools flat-analysis idiom: a constant '.flag_' tabulated with the
  # group as `by` (per-group percentage denominators).  In generated code
  # this branch coexists with the by/strata branches, whose
  # `variables = <group var>` call carries the same analysis -- skip this
  # one so the de-duplication step sees a single emission.
  if (identical(vars, ".flag_")) {
    return(invisible())
  }
  # siera-generated subject-count idiom: distinct subjects + variables='dummy'
  if (identical(vars, "dummy")) {
    .apc_emit(st, "categorical_summary", "USUBJID", cx$by, cx$info,
              name = paste0("Subjects by ", paste(cx$by, collapse = " and ")),
              denominator = if (!is.null(den)) "auto" else "")
    return(invisible())
  }
  # big-N idiom: single variable, no by / denominator
  if (length(cx$by) == 0 && length(vars) == 1 && is.null(den)) {
    .apc_emit(st, "total_n", "USUBJID", vars, cx$info,
              name = "Number of subjects")
    st$note(paste0("ASSUMED: ard_tabulate(variables = ", vars,
                   ") with no by/denominator read as a big-N count by ", vars,
                   " (subject-count assumption)."))
    return(invisible())
  }
  for (v in vars) {
    .apc_emit(st, "categorical_summary", "USUBJID", c(cx$by, v), cx$info,
              name = paste0(v, ", n (%)"), denominator = "auto")
    st$note(paste0("ASSUMED: ard_tabulate(", v, ") mapped to subject-count ",
                   "n (%) (variable=USUBJID, ", v, " as 2nd grouping); a ",
                   "total_n analysis supplies the denominator."))
  }
}

.apc_h_stack <- function(e, st) {
  info <- .apc_data_info(.apc_arg_data(e), st)
  by <- .apc_chr_vec(.apc_arg(e, ".by"), st)
  ctx <- list(info = info, by = by)
  total_n <- .apc_arg(e, ".total_n")
  if (!is.null(total_n) && identical(deparse(total_n), "TRUE")) {
    .apc_emit(st, "total_n", "USUBJID", by, info, name = "Number of subjects")
  }
  nm <- names(e); if (is.null(nm)) nm <- rep("", length(e))
  for (i in seq_along(e)[-1]) {
    if (nzchar(nm[i])) next
    part <- e[[i]]
    if (!is.call(part)) next
    f <- .apc_fname(part)
    if (f %in% c("ard_summary", "ard_continuous")) {
      .apc_h_continuous(part, st, ctx)
    } else if (f %in% c("ard_tabulate", "ard_categorical")) {
      .apc_h_tabulate(part, st, ctx)
    } else if (grepl("^ard_", f)) {
      st$note(paste0("Unsupported ARD function inside ard_stack() skipped: ",
                     f, "()"))
    }
  }
}

.apc_h_stack_hier <- function(e, st) {
  info <- .apc_data_info(.apc_arg_data(e), st)
  by <- .apc_chr_vec(.apc_arg(e, "by"), st)
  vars <- .apc_chr_vec(.apc_arg(e, "variables"), st)
  over <- .apc_arg(e, "over_variables")

  if (!is.null(over) && identical(deparse(over), "TRUE")) {
    .apc_emit(st, "categorical_summary", "USUBJID", by, info,
              name = "Subjects with at least one event, n (%)",
              denominator = "auto")
    return(invisible())
  }
  if (length(vars) >= 2) {
    st$note(paste0("LIMITATION: ard_stack_hierarchical(",
                   paste(vars, collapse = " > "), ") is a nested display (",
                   length(vars) + 1, " groupings incl. arm); the compact ",
                   "format supports 2, so FLAT by-",
                   paste(vars, collapse = " / by-"),
                   " analyses were generated instead (ydisctools #6)."))
  }
  for (v in vars) {
    .apc_emit(st, "categorical_summary", "USUBJID", c(by, v), info,
              name = paste0("Events by ", v, ", n (%)"),
              denominator = "auto")
  }
  den <- .apc_arg(e, "denominator")
  if (!is.null(den)) {
    dinfo <- .apc_data_info(den, st)
    if (!is.null(dinfo)) {
      .apc_emit(st, "total_n", "USUBJID", by, dinfo,
                name = "Number of subjects")
      st$note(paste0("ASSUMED: hierarchical `denominator=` dataset emitted ",
                     "as a total_n analysis (the n(%) analyses reference it ",
                     "via denominator='auto')."))
    }
  }
}

.apc_cardx_map <- c(
  ard_stats_fisher_test = "fishers_exact",
  ard_stats_chisq_test  = "chisq",
  ard_stats_aov         = "anova",
  ard_stats_anova       = "anova",
  ard_stats_oneway_test = "anova",
  ard_stats_prop_test   = "risk_difference"
)

.apc_h_cardx <- function(e, st) {
  f <- .apc_fname(e)
  method <- .apc_cardx_map[[f]]
  cx <- .apc_ctx_of(e, st, NULL)
  vars <- .apc_chr_vec(.apc_arg(e, "variables"), st)
  for (v in vars) {
    .apc_emit(st, method, v, cx$by, cx$info,
              name = paste0(v, " (", method, ")"))
  }
  st$note(paste0("MAPPED: ", f, "() -> catalog method '", method,
                 "' - review that the operations match the intent."))
}

# -- display furniture extraction ---------------------------------------------

.apc_add_disp <- function(st, type, text) {
  text <- text[!is.na(text) & nzchar(trimws(text))]
  for (t in text) {
    st$disp[[length(st$disp) + 1L]] <- list(section_type = type, order = 0L,
                                            text = t)
  }
}

# rtf_header(rows = list(c(l=, r=), c(c=), ...)) / rtf_footer(rows = ...)
# Classification heuristics (noted): header rows that are centred-only are
# titles; footer rows carrying only a plain left text are footnotes.
.apc_h_furniture <- function(e, st, kind) {
  rows <- .apc_null_default(.apc_arg(e, "rows"), .apc_arg(e, "text"))
  if (is.null(rows)) return(invisible())
  elements <- if (is.call(rows) && .apc_fname(rows) == "list") {
    as.list(rows)[-1]
  } else {
    list(rows)
  }
  for (el in elements) {
    if (is.character(el)) {
      .apc_add_disp(st, if (kind == "rtf_header") "Header" else "Footer", el)
      next
    }
    if (!(is.call(el) && .apc_fname(el) == "c")) next
    parts <- as.list(el)[-1]
    nm <- names(el)[-1]
    if (is.null(nm)) nm <- rep("", length(parts))
    lit <- vapply(parts, function(p) {
      if (is.character(p)) p else NA_character_
    }, character(1))
    if (anyNA(lit)) {
      st$note(paste0("REVIEW: dynamic ", kind, " row skipped: `",
                     paste(deparse(el), collapse = " "), "`"))
      next
    }
    if (kind == "rtf_header") {
      type <- if (all(nm == "c")) "Title" else "Header"
    } else {
      type <- if (length(parts) == 1 && nm[1] %in% c("l", "")) {
        "Footnote"
      } else {
        "Footer"
      }
    }
    .apc_add_disp(st, type, lit)
  }
  st$note(paste0("ASSUMED: ", kind, "() rows were classified ",
                 if (kind == "rtf_header") {
                   "(centred-only rows -> Title, left/right rows -> Header)"
                 } else {
                   "(single plain rows -> Footnote, left/right rows -> Footer)"
                 }, " - review the Displays sheet."))
}

# titles = / footnotes = arguments (rtf_titles / rtf_footnotes / rtf_tables)
.apc_h_text_args <- function(e, st) {
  for (spec in c("titles", "footnotes")) {
    a <- .apc_arg(e, spec)
    if (is.null(a)) next
    texts <- .apc_all_literals(a)
    .apc_add_disp(st, if (spec == "titles") "Title" else "Footnote", texts)
    if (length(texts) == 0) {
      st$note(paste0("REVIEW: `", spec, "=` present but no static text ",
                     "could be extracted."))
    }
  }
}

.apc_all_literals <- function(e) {
  if (is.character(e)) return(e)
  if (is.call(e) && .apc_fname(e) %in% c("c", "list")) {
    return(unlist(lapply(as.list(e)[-1], .apc_all_literals)))
  }
  character(0)
}

# col_header assignments: the first STATIC element is the row-label header
.apc_capture_col_header <- function(rhs, st) {
  if (is.call(rhs) && .apc_fname(rhs) == "c") {
    first <- as.list(rhs)[[2]]
    if (is.character(first)) {
      .apc_add_disp(st, "Rowlabel Header",
                    trimws(gsub("\\s*\n\\s*", " ", first)))
      st$note("ASSUMED: the first static col_header element was captured as the Rowlabel Header display subsection; grouping columns come from the ARS groupings.")
      return(invisible())
    }
  }
  st$note("REVIEW: a col_header assignment was found but its first element is not static text; Rowlabel Header not captured.")
}
